project_id = "jhtnruktmtjqrfoiyrep"

[functions.evaluate-problem-statement]
verify_jwt = true

[functions.submit-startup-public]
verify_jwt = false

[functions.generate-startup-section-summary]
verify_jwt = true

[functions.clear-section-summaries]
verify_jwt = true

[functions.submit-and-evaluate-startup]
verify_jwt = false

[functions.startup-market-research]
verify_jwt = true

[functions.backfill-startup-research]
verify_jwt = true