project_id = "jhtnruktmtjqrfoiyrep"

[functions.evaluate-problem-statement]
verify_jwt = true

[functions.submit-startup-public]
verify_jwt = false

[functions.generate-startup-section-summary]
verify_jwt = true

[functions.submit-and-evaluate-startup]
verify_jwt = false